

wow:
  command:
    bus:
      type: redis
  event:
    bus:
      type: redis
  eventsourcing:
    state:
      bus:
        type: redis
    store:
      storage: mongo
    snapshot:
      storage: mongo

  kafka:
    enabled: false
  mongo:
    enabled: true
    auto-init-schema: true
    event-stream-database: natty
    snapshot-database: natty
    prepare-database: natty
  redis:
    enabled: true
  prepare:
    storage: redis


simba:
  redis:
    enable: true
  jdbc:
    enable: false