management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - cosid
          - cosidGenerator
          - cosidStringGenerator
springdoc:
  show-actuator: true

spring:
  main:
    web-application-type: reactive
  application:
    name: natty-wow
  jackson:
    serialization:
      write-durations-as-timestamps: true
      write-dates-as-timestamps: true
    mapper:
      accept-case-insensitive-enums: true
  profiles:
    active: local

logging:
  level:
    me.ahoo.wow: debug
cosid:
  machine:
    enabled: true
    distributor:
      type: manual
      manual:
        machine-id: 1
  generator:
    enabled: true
wow:
  kafka:
    enabled: false
  command:
    bus:
      type: in_memory
  event:
    bus:
      type: in_memory
  eventsourcing:
    store:
      storage: in_memory
    snapshot:
      storage: in_memory
    state:
      bus:
        type: in_memory